import Head from 'next/head'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faInstagram } from "@fortawesome/free-brands-svg-icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jaclyn Rae Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* NAV */}
      <section>
        <div class="navbar bg-base-100 max-h-40">
          {/*TODO: get this image to fit*/}
          {/* <div > */}
            <img src="/logo.webp" class="h-20 w-20 flex justify-center absolute content-center m-10" />
          {/* </div> */}
          {/*TODO: get this svg to fit*/}
          {/* <FontAwesomeIcon icon={faInstagram} /> */}
        </div>
      </section>


      {/* HERO */}
      <section>
        <div class="hero min-h-screen bg-base-200">
          <div class="hero-content flex-col lg:flex-row">
            <img src="/jaclynHero.webp" class="max-w-sm rounded-lg shadow-2xl" />
            <div>
              <h1 class="text-4xl font-bold">Welcome</h1>
              <p class="py-6 max-w-sm">My name is Jaclyn. I'm a 200-hour certified yoga teacher. I'd love to see you on the mat. Please see my class schedule for when I'm teaching next.</p>
              <button class="btn btn-accent">See Class Schedule</button>
            </div>
          </div>
        </div>    
      </section>
  

      {/* CLASS SCHEDULE */}

      {/* ABOUT */}

      {/* TESTIMONIALS */}

      {/* NEWSLETTER */}

      {/* FOOTER */}
      <section>
        <footer class="footer items-center p-4 bg-accent text-neutral-content">
          <div class="items-center grid-flow-col">
            <p>Copyright © {new Date().getFullYear()} - All right reserved</p>
          </div>
          <div class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
            <a class="h-50 w-50" href="https://instagram.com/jaclynraeyoga"></a>
          </div>
        </footer>
      </section>

    </>
  )
}
